apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-suite
  namespace: media
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jellyfin.example.org
    - jellyseer.example.org
    - prowlarr.example.org
    - qbittorrent.example.org
    - radarr.example.org
    - sonarr.example.org
    secretName: media-suite-tls
  rules:
  - host: jellyfin.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 80
  - host: jellyseer.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseer
            port:
              number: 80
  - host: qbittorrent.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 80              
  - host: prowlarr.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80   
  - host: radarr.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
  - host: sonarr.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80
  - host: immich.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80     
  - host: cloud.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80
  - host: homepage.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80